HW-version1
mate-academy/jv-oop-advanced pull request #1084
Opened 2023-05-14 14:20 UTC by stas83ggg

2023-05-14 15:12 UTC, okuzan requested changes
Please make sure the build passes before requesting a review 🙏

2023-05-16 10:34 UTC, aaananas requested changes

2023-05-16 10:34 UTC, aaananas commented on src/main/java/core/basesyntax/FigureSupplier.java
> +            case 2:
```suggestion
                return getRandomCircle();
            case 1:
                return getRandomIsoscelesTrapezoid();
            case 2:
```
lets divide the logic into smaller private methods - it makes it easier to read your code

2023-05-16 10:34 UTC, aaananas commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    }
```suggestion
    public Figure getDefaultFigure() { 
        return new Circle(DEFAULT_RADIUS, DEFAULT_COLOR);
    }
```
avoid magic numbers ✨ 
use constants

2023-05-16 10:34 UTC, aaananas commented on src/main/java/core/basesyntax/Figure.java
> +
```suggestion
public abstract class Figure implements Area, DrawArea {
    private String color;

    public Figure(String color) {
        this.color = color;
    }
```

2023-05-16 10:34 UTC, aaananas commented on src/main/java/core/basesyntax/Circle.java
> +    }
```suggestion
    public Circle(String color, int radius) {
        super(color);
        this.radius = radius;
    }
```
you can call parent class constructor

2023-05-16 19:16 UTC, closed without merging

2023-05-16 19:16 UTC, stas83ggg commented
Will be new version