jv-oop-advanced task completed 1 commit
mate-academy/jv-oop-advanced pull request #1100
Opened 2023-05-30 21:02 UTC by happytroya

2023-05-31 09:49 UTC, okuzan requested changes
Please fix the build before rerequesting review. Also, check you files and delete extra empty lines. There should be only one loop in Main. Rethink your hierarchy - should Figure be interface or abstract class? What interfaces should you implement? Color is common for all figures - would make sense to call parent constructor here

2023-05-31 14:50 UTC, Ivan95kos requested changes

2023-05-31 14:50 UTC, Ivan95kos commented on src/main/java/core/basesyntax/FigureMaths.java
> +public interface FigureMaths {
```suggestion
public interface AreaCalculator {
```

2023-05-31 14:50 UTC, Ivan95kos commented on src/main/java/core/basesyntax/Figure.java
> +    public abstract void draw();
You must create a Drawable interface with this method

2023-05-31 14:50 UTC, Ivan95kos commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        Figure[] figures = {
Creat each figure in privete method

2023-05-31 14:50 UTC, Ivan95kos commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        return figures[random.nextInt(figures.length - 1)];
use swich case for this action

2023-05-31 14:50 UTC, Ivan95kos commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        return new Circle(10, Color.WHITE);
All magic numbers, strings, symbols in your code should be constants.
[this article](https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names)

2023-05-31 14:50 UTC, Ivan95kos commented on src/main/java/core/basesyntax/FigureSupplier.java
> +                        random.nextInt(10),
use constants instead of numbers

2023-05-31 16:40 UTC, Ivan95kos requested changes
Good job overall!

2023-05-31 16:40 UTC, Ivan95kos commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        int figureNumber = random.nextInt(5);
use constants instead of number

2023-06-01 10:09 UTC, hronograf approved these changes

2023-06-01 10:09 UTC, hronograf commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private static final int MAX_INT = 10;
It would be good to have a separate constant for the default circle radius and max value of figure properties
so we can change them separately

2024-05-13 10:42 UTC, closed without merging