idk how to sout info about specific figures and how to adress to spec…
mate-academy/jv-oop-advanced pull request #1201
Opened 2023-08-02 08:26 UTC by tsuki99

…ific figure to print info about it

2023-08-02 09:36 UTC, overpathz requested changes
You have a failing maven build.
Please, check it for mistakes/checkstyle errors and request review again.

2023-08-19 09:54 UTC, olekskov requested changes

2023-08-19 09:54 UTC, olekskov commented on src/main/java/core/basesyntax/Color.java
> +    Pink
enum values are technically constants with PROPER_NAMING convention

2023-08-19 09:54 UTC, olekskov commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        int index = new Random().nextInt(colors.length);
Please extract Random as class variable in order not to create new object each time method is called

2023-08-19 09:54 UTC, olekskov commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        int randomIndex = new Random().nextInt(FIGURE_AMOUNT);
Please extract Random as class variable in order not to create new object each time methods are called (same as done for ColorSupplier)

2023-08-19 09:54 UTC, olekskov commented on src/main/java/core/basesyntax/Main.java
> +    private static final int SIX_FIGURES = 6;
Naming should be based on purpose, not value itself
```suggestion
    private static final int FIGURES_AMOUNT = 6;
```

2023-08-19 09:54 UTC, olekskov commented on src/main/java/core/basesyntax/Main.java
> +            }
Extract common part from if/else
```suggestion
            if (i < figures.length / HALF) {
                figures[i] = figureSupplier.getRandomFigure();
            } else {
                figures[i] = figureSupplier.getDefaultFigure();
            }
            figures[i].draw();
```

2023-08-20 09:30 UTC, kozhukhovsky requested changes

2023-08-20 09:30 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Circle.java
> +
```suggestion
```

2023-08-20 09:30 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    private static final Color[] colors = Color.values();
no need to put it in a variable

2023-08-20 09:30 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Circle.java
> +    private static final int TEN = 10;
Not quite the correct name. The fact that it is 10 is already visible, but why 10, what is it?

2023-08-20 09:30 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    public Figure getDefaultFigure() {
all public methods go first, then all private ones

2023-08-20 09:30 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/IsoscelesTrapezoid.java
> +    private static final int TWO = 2;
same

2023-08-20 09:30 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/IsoscelesTrapezoid.java
> +
```suggestion
```

2023-08-20 09:30 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Main.java
> +    private static final int START_INDEX = 0;
there is no need to put it in a variable either

2023-08-20 09:30 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Rectangle.java
> +
```suggestion
```

2023-08-20 09:30 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/RightTriangle.java
> +    private static final int TWO = 2;
same

2023-08-20 14:36 UTC, aaananas approved these changes

2025-08-26 19:42 UTC, closed without merging