Added jv-oop-advanced solution
mate-academy/jv-oop-advanced pull request #1217
Opened 2023-08-09 15:42 UTC by Stanislav-Viner

2023-08-10 09:57 UTC, olekskov requested changes

2023-08-11 14:38 UTC, kozhukhovsky requested changes

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    enum Color { WHITE, BLACK, RED, BLUE, GREEN }
move enum to the separate class

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ColorSupplier.java
> +
```suggestion
```

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    enum Shape { CIRCLE, SQUARE, RECTANGLE, TRIANGLE, TRAPEZOID }
move to the separate enum class

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/FigureSupplier.java
> +
```suggestion
```

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/FigureSupplier.java
> +
```suggestion
```

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        switch (Shape.values()[random.nextInt(Shape.values().length)]) {
```suggestion
        Shape shape = Shape.values()[random.nextInt(Shape.values().length)]
        switch (shape) {
```

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    public Figure getDefoltFigure() {
```suggestion
    public Figure getDefaultFigure() {
```

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        return new Circle(10, ColorSupplier.Color.WHITE.name());
move 10 to the constant, because its magic number

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Main.java
> +
```suggestion
```

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Main.java
> +        for (Figure figure : figures) {
Just make a loop of 6 iterations. In the first half, call getRandomFigure, in the second half, getDefaultFigure

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Main.java
> +        Figure[] figures = new Figure[] {randomFigureOne, randomFigureTwo, defoltFigure};
```suggestion
```

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Area.java
> +public interface Area {
```suggestion
public interface AreaСalculable {
```

2023-08-11 14:38 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Figure.java
> +    public abstract String printInfo();
create separate interface "Drawable" for this method, like Area

2023-08-15 09:59 UTC, overpathz requested changes
Need some fixes

2023-08-15 09:59 UTC, overpathz commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    private Random random = new Random();
Since object will never change, you can make it final

2023-08-15 09:59 UTC, overpathz commented on src/main/java/core/basesyntax/Drawable.java
> +    String printInfo();
I would better name it as draw(), since name of interface is Drawable

2023-08-15 09:59 UTC, overpathz commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private Random random = new Random();
Make it final as well

2023-08-15 09:59 UTC, overpathz commented on src/main/java/core/basesyntax/FigureSupplier.java
> +                return new Circle(random.nextInt(10) + 1,
Magic numbers. You can do constant like MAX_RANDOM_NUMBER and create the static private method getRandomNumber() which will contain `random.nextInt(MAX_RANDOM_NUMBER)`

2023-08-15 09:59 UTC, overpathz commented on src/main/java/core/basesyntax/FigureSupplier.java
> +                return new Square(random.nextInt(10) + 1,
It would be better if you make methods for returning figures and use it instead of creating objects via new directly

2023-08-15 15:21 UTC, Ivan95kos requested changes
Few comments left

2023-08-15 15:21 UTC, Ivan95kos commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private static final ColorSupplier colorSupplier = new ColorSupplier();
These fields should not be the `static`
```suggestion
    private final Random random = new Random();
    private final ColorSupplier colorSupplier = new ColorSupplier();
```

2023-08-15 15:21 UTC, Ivan95kos commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private static int getRandomNumber() {
the same
```suggestion
    private int getRandomNumber() {
```

2023-08-15 16:29 UTC, Ivan95kos approved these changes
Nice

2023-08-15 16:47 UTC, closed without merging