Oop HW adv solution
mate-academy/jv-oop-advanced pull request #1251
Opened 2023-08-28 10:12 UTC by luk14n

2023-08-28 10:59 UTC, Rommelua requested changes

2023-08-28 10:59 UTC, Rommelua commented on src/main/java/core/basesyntax/Circle.java
> +        this.color = color;
```suggestion
        super(color);
        this.radius = radius;
```

2023-08-28 10:59 UTC, Rommelua commented on src/main/java/core/basesyntax/Color.java
> +}
```suggestion
    BLUE
}
```

2023-08-28 10:59 UTC, Rommelua commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private static final int MAGIC_NUMBER = 100;
```suggestion
    private static final int MAX_LENGTH = 100;
```

2023-08-28 10:59 UTC, Rommelua commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        final int randomProperty2 = random.nextInt(MAGIC_NUMBER);
in case of Circle you do not need them. Do not create redundant ones.

2023-08-28 10:59 UTC, Rommelua commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        return new Circle(10, Color.WHITE.name());
add constants (DEFAULT_RADIUS, ..)

2023-11-01 15:15 UTC, Sanderfuck requested changes

2023-11-01 15:15 UTC, Sanderfuck commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private static final String DEFAULT_COLOR = "white";
You can use value from enum

2023-11-01 15:15 UTC, Sanderfuck commented on src/main/java/core/basesyntax/RightTriangle.java
> +    }
Try to save same order of methods in every class

2023-11-01 15:58 UTC, Sanderfuck approved these changes

2023-11-01 18:27 UTC, closed without merging