Homework
mate-academy/jv-oop-advanced pull request #1316
Opened 2023-10-09 12:44 UTC by maxymmusiienko

made abstract figure class and 5 figures, added color and figure supliers for creating new figures

2023-10-09 14:59 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2023-10-09 14:59 UTC, Rommelua commented on src/main/java/core/basesyntax/Area.java
> +public interface Area {
```suggestion
public interface AreaCalculator {
```

2023-10-09 14:59 UTC, Rommelua commented on src/main/java/core/basesyntax/Drawer.java
> +public interface Drawer {
```suggestion
public interface Drawable {
```

2023-10-09 14:59 UTC, Rommelua commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        int choice = random.nextInt(5);
![image](https://github.com/mate-academy/jv-oop-advanced/assets/20326858/dcfd4a98-305e-4cb9-85a5-ca0c3beff47b)

2023-10-10 11:59 UTC, kozhukhovsky requested changes

2023-10-11 10:31 UTC, okuzan requested changes

2023-10-11 10:31 UTC, okuzan commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        return new Circle(Color.WHITE, DEFAULT_RADIUS);
make enum value a DEFAULT_COLOR constant

2023-10-11 10:31 UTC, okuzan commented on src/main/java/core/basesyntax/FigureSupplier.java
> +                        random.nextDouble() * 10 + 1);
extract random.nextDouble() * 10 + 1 to a private method,  make 10 a constant

2023-10-11 10:31 UTC, okuzan commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private static final Random random = new Random();
```suggestion
    private final Random random = new Random();
```
should be same as color supplier

2023-10-11 10:31 UTC, okuzan commented on src/main/java/core/basesyntax/Main.java
> +        }
can be done in one loop. use length/2

2023-10-11 10:31 UTC, okuzan commented on src/main/java/core/basesyntax/Main.java
> +        final int N = 6;
make it a class constant with a more meaningful name :)

2023-10-11 20:49 UTC, Ivan95kos approved these changes
Great job, with a minor comment

2023-10-11 20:49 UTC, Ivan95kos commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private double getRandomSide() {
All private methods should be below public methods

2026-05-28 12:29 UTC, closed without merging