solved the task using oop
mate-academy/jv-oop-advanced pull request #1320
Opened 2023-10-11 12:41 UTC by aksoli666

principles
realised the following classes:
BaseFigure, Circle, ColorSupplier,
FigureSupplier,
IsoscelesTrapezoid, Main,
Rectangle, RightTriangle, Square;
realised the following interfaces:
Figure, AreaAble;
and enum -> Color;

2023-10-11 14:13 UTC, sokimaaa commented on src/main/java/core/basesyntax/AreaAble.java
> +public interface AreaAble {
```suggestion
public interface AreaCalculator {
```

2023-10-11 14:15 UTC, sokimaaa requested changes

2023-10-12 09:21 UTC, Rommelua requested changes

2023-10-12 09:21 UTC, Rommelua commented on src/main/java/core/basesyntax/Drawable.java
> +    void draw();
![image](https://github.com/mate-academy/jv-oop-advanced/assets/20326858/3796ca63-6828-4d46-b8b4-a6a68a4807db)

2023-10-12 09:21 UTC, Rommelua commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        return new Circle(10, color);
![image](https://github.com/mate-academy/jv-oop-advanced/assets/20326858/e0d9f548-2f83-42c0-aeda-54bf19892c28)

2023-10-12 16:21 UTC, sokimaaa approved these changes

2024-06-21 20:18 UTC, closed without merging