release generator random figure
mate-academy/jv-oop-advanced pull request #1397
Opened 2023-12-20 21:55 UTC by u3IOm4uk

2023-12-21 11:15 UTC, kozhukhovsky requested changes

2023-12-21 11:15 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Figure.java
> +    private Color color = new ColorSupplier().getRandomColor();
```suggestion
    private Color color;
```

2023-12-21 11:15 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Figure.java
> +    private Color color = new ColorSupplier().getRandomColor();
It is necessary not to set the color here, but to pass it through the constructor during creation.

2023-12-21 11:15 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Main.java
> +
```suggestion
```

2023-12-21 11:15 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/enums/Color.java
> +    black,
```suggestion
    BLACK,
```

2023-12-21 11:15 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/enums/Color.java
> +    black,
in enam all items come in the upper case

2023-12-21 11:15 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/enums/FigureName.java
> +public enum FigureName {
same

2023-12-21 11:15 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/figure/FigureSupplier.java
> +        return new Circle(10, Color.white);
move 10 to the constant

2023-12-21 11:15 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/interfaces/Area.java
> +public interface Area {
```suggestion
public interface AreaCalculator {
```

2023-12-21 11:15 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/interfaces/Draw.java
> +public interface Draw {
```suggestion
public interface Drawable {
```

2023-12-21 19:57 UTC, Sanderfuck requested changes

2023-12-21 19:57 UTC, Sanderfuck commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Color.values()[indexColor];
Return color in String value

2023-12-21 19:57 UTC, Sanderfuck commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    private int indexColor;
This field is redundant

2023-12-21 19:57 UTC, Sanderfuck commented on src/main/java/core/basesyntax/Figure.java
> +    }
Don`t init color in this class

2023-12-21 19:57 UTC, Sanderfuck commented on src/main/java/core/basesyntax/figure/Circle.java
> +    }
You don`t need 2 constructors here

2023-12-21 19:57 UTC, Sanderfuck commented on src/main/java/core/basesyntax/figure/FigureSupplier.java
> +                double side = random.nextInt(boundMin, boundMax);
Duplication code, you can take out in separate method

2023-12-22 20:09 UTC, Ivan95kos requested changes
Please, fix all previous comments

2023-12-22 20:09 UTC, Ivan95kos commented on src/main/java/core/basesyntax/Figure.java
> +    }
not fixed

2023-12-22 20:09 UTC, Ivan95kos commented on src/main/java/core/basesyntax/figure/FigureSupplier.java
> +    public int randomParameters() {
Methods that use only in class should be private
```suggestion
    private int randomParameters() {
```

2023-12-22 20:09 UTC, Ivan95kos commented on src/main/java/core/basesyntax/figure/FigureSupplier.java
> +    private final int defaultRadius = 10;
Make them constants

2023-12-22 20:09 UTC, Ivan95kos commented on src/main/java/core/basesyntax/figure/FigureSupplier.java
> +    private int indexFigureName;
This field should be in the method

2023-12-22 20:09 UTC, Ivan95kos commented on src/main/java/core/basesyntax/figure/FigureSupplier.java
> +                return null;
```suggestion
                return getDefaultFigure();
```

2023-12-22 20:09 UTC, Ivan95kos commented on src/main/java/core/basesyntax/figure/FigureSupplier.java
> +        circle.setColor("WHITE");
Use Enum and constant
```suggestion
        circle.setColor(DEFAULT_COLOR);
```

2023-12-22 20:09 UTC, Ivan95kos commented on src/main/java/core/basesyntax/interfaces/Drawable.java
> +    String draw();
You should draw the Figure inside of method
```suggestion
    void draw();
```

2023-12-23 17:37 UTC, Ivan95kos approved these changes
Great job, with minor comments

2023-12-23 17:37 UTC, Ivan95kos commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    }
Make a constant `DEFAULT_COLOR` in `FigureSupplier`
```suggestion
```

2023-12-23 17:37 UTC, Ivan95kos commented on src/main/java/core/basesyntax/figure/FigureSupplier.java
> +        final int defaultRadius = 10;
it must be a constant
```suggestion
```

2024-05-09 16:04 UTC, closed without merging