It's working:)
mate-academy/jv-oop-advanced pull request #14
Opened 2020-12-01 20:08 UTC by Max-Pochepets

2020-12-02 09:12 UTC, Sofasmile requested changes
Be attentive! We shouldn't do hw in `master` branch. We have to create new branch and do hw there.
![image](https://user-images.githubusercontent.com/36365171/100846938-cb3e0200-3487-11eb-8af4-d1d0bc8cfd3c.png)

2020-12-02 09:12 UTC, Sofasmile commented on src/main/java/core/basesyntax/Main.java
> +    public static void main(String[] args) {
method main should only run the program. Let's move the logic for generating figures to a separate class - Figure Generator

2020-12-02 09:12 UTC, Sofasmile commented on src/main/java/core/basesyntax/Main.java
> +            switch (random.nextInt(6) + 1) {
6 is a magic number)
let's create a constant for it - https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names

2020-12-02 09:30 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/figures/Shape.java
> +public abstract class Shape implements Figure {
Shape is abstract class to be able to create an array of figures. Figure, on the other hand, is an interface.

2020-12-02 10:54 UTC, Sofasmile requested changes

2020-12-02 10:54 UTC, Sofasmile commented on src/main/java/core/basesyntax/Main.java
> +    public static Shape[] generateFigures(int count) {
let's move this method to the separate class

2020-12-02 10:54 UTC, Sofasmile commented on src/main/java/core/basesyntax/Main.java
> +    static final int COLORS = 6;
let's add access modifiers

2020-12-02 10:54 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Circle.java
> +        this.radius = RandomNumber.getRandomNumber(20);
how about this comment? 
https://github.com/mate-academy/jv-oop-advanced/pull/14#discussion_r533991229
I meant that we should pass a random value through the constructor:
```
new Circle(RandomNumber.getRandomNumber(20));
```
The same with other figures

2020-12-02 10:54 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Figure.java
> +public interface Figure {
better make Figure as a class and add some fields

2020-12-02 10:54 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Figure.java
> +    static HashMap<Integer, String> generateColors() {
let's move this method to the separate class or to the FigerGenerator

2020-12-02 10:54 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Shape.java
> +public abstract class Shape implements Figure {
What is the conceptual difference between Shape and Figure? Let's remove Shape class and make Figure as abstract class

2020-12-02 18:49 UTC, Sofasmile requested changes

2020-12-02 18:49 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureOps.java
> +    static final int COLORS = 6;
варто додати модифікатор доступу

2020-12-02 18:49 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureOps.java
> +    static final int COLORS = 6;
```suggestion
    static final int NUMBER_OF_COLORS = 6;
```

2020-12-02 18:49 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureOps.java
> +    public static void drawFigure(Shape[] figures) {
цей метод не відносить до генерації фігур, тому давай його перенесемо в Main клас

2020-12-02 18:49 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Angled.java
> +public interface Angled {
давай видалимо цей інтерфейс і метод що в ньому))
якщо все ж таки хочеш обраховувати периметр - то краще перейменувати цей інтерфейс і метод зробити не дефолтним а абстрактним

2020-12-02 18:49 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Shape.java
> +    protected String color;
поле повинно бути приватним

2020-12-02 18:49 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Circle.java
> +
пусту строку вкінці методу варто видалити

2020-12-02 18:49 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Rounded.java
> +public interface Rounded {
давай тут також обійдемось без інтерфейса, а просто створимо метод в класі коло

2020-12-02 18:49 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Shape.java
> +        this.color = generateColors().get(RandomNumber.getRandomNumber(3));
генерувати колір потрібно в класі FigureOps і при своренні об'єктів фігури присвоювати згенероване значення.

2020-12-02 18:49 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Shape.java
> +    public abstract void draw();
цей метод рекомендую винести в окремий інтерфейс

2020-12-02 18:49 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Shape.java
> +    private static HashMap<Integer, String> generateColors() {
цей метод перенести в клас FigureOps

2020-12-03 10:07 UTC, Sofasmile requested changes

2020-12-03 10:07 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Circle.java
> +    }
```suggestion
    public Circle(int value, String color) {
        super(color);
        this.radius = value;
    }
```

2020-12-03 10:07 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Circle.java
> +        return super.getColor();
якщо ми зберігаємо колір в класі Shape і там є метод getColor() то в усіх класах наслідниках можна видалити цей метод. Він і так буде доступний

2020-12-03 10:07 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/RightTriangle.java
> +        double s = (legA + legB + getHypotenuse()) / 2; // Heron
```suggestion
        double s = (legA + legB + getHypotenuse()) / 2; 
```

2020-12-03 10:07 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Shape.java
> +public abstract class Shape implements Drawable {
якщо ми тут імплементуємо інтерфейс то в класах наслідниках ми можемо його не імплементити

2020-12-03 10:14 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/figures/Circle.java
> +        return super.getColor();
You can type in English, I understand :) I understand, but not always agree, that's why I ignored some requests, and that's why, I think, u started typing in English. But I asked Bohdan today, and I understand what u trying to accomplish and I need to act in this type of situations. Thanks :)

2020-12-03 11:13 UTC, Sofasmile approved these changes

2020-12-03 11:13 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Triangle.java
>  public class Triangle extends Shape implements Drawable {
```suggestion
public class Triangle extends Shape {
```

2020-12-03 11:14 UTC, Sofasmile commented on src/main/java/core/basesyntax/figures/Circle.java
> +        return super.getColor();
Домовились) На майбутнє, якщо ти не розумієш якісь коментарі - то пиши в слеку - я з радістю відповім

2020-12-03 11:16 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/figures/Circle.java
> +        return super.getColor();
> Домовились) На майбутнє, якщо ти не розумієш якісь коментарі - то пиши в слеку - я з радістю відповім

👍

2021-04-01 06:08 UTC, closed without merging