make solution
mate-academy/jv-oop-advanced pull request #151
Opened 2021-06-16 17:08 UTC by dmitriy-tverdokhlibov

2021-06-16 17:20 UTC, dmitriy-tverdokhlibov commented
У меня там bug в классе СolorSupplier в 26 строке. Сейчас буду исправлять

2021-06-17 06:27 UTC, RomanDubovskyi requested changes

2021-06-17 06:27 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/Circle.java
> +        System.out.println(new StringBuilder().append("Figure: ").append(getName())
тут можна юзати String якщо це статичні дані, їх компілятор переведе в StringBuilder під капотом, маст хев використовувати білдер у циклах з конкатинацією

2021-06-17 06:27 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        String[] colors = new String[5];
5 - magic number, оголоси змінну colorsAmount і використай її, це покращить читаймість

2021-06-17 06:27 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        setColor(colors[random.nextInt(5)]);
```suggestion
       return colors[random.nextInt(5)];
```
і можна буде витерти змінну color

2021-06-17 06:27 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/Circle.java
> +public class Circle extends Figure implements Drawing {
```suggestion
public class Circle extends Figure {
```
зроби щоб в тебе клас Figure реалізовував Drawing і не потрібно буде це вручну в кожному класі робити

2021-06-17 06:27 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        Figure[] figures = new Figure[5];
аналогічно тут з 5

2021-06-18 06:40 UTC, RomanDubovskyi approved these changes

2021-06-18 06:40 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/FigureSupplier.java
> +            figureArrayForReturn[i] = figures[(int) (Math.random() * 5)];
```suggestion
            figureArrayForReturn[i] = figures[(int) (Math.random() * figures.length)];
```

2021-06-18 06:40 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/Square.java
> +public class Square extends Figure implements Drawing {
```suggestion
public class Square extends Figure {
```

2021-06-18 06:40 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return colors[random.nextInt(5)];
```suggestion
        return colors[random.nextInt(colors.length)];
```
таким чином якщо розмір масиву зміниться тут не потрібно буде нічого додатково міняти

2021-06-18 16:28 UTC, dmitriy-tverdokhlibov commented on src/main/java/core/basesyntax/Square.java
> +public class Square extends Figure implements Drawing {
Куда я смотрел(

2021-06-18 16:35 UTC, dmitriy-tverdokhlibov commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return colors[random.nextInt(5)];
Ок, спасибо Рома

2025-04-23 19:02 UTC, closed without merging