in Main class: create random number to create same number of figures;…
mate-academy/jv-oop-advanced pull request #158
Opened 2021-07-08 22:39 UTC by ablindaruk

… create array with same length; create figures and fill in array - one loop; call method to draw data about each figure - second loop.

in Figure class: abstract method for color as state to get body in subclasses; implement 2 interfaces - one to obtain area in definite figure subclass, second to draw data from definite figure subclass.

in FigureSupplier class: generate all random numbers; choose and create figures.

2021-07-09 04:48 UTC, ablindaruk commented
Добрый день. Не пойму, что надо исправить и ошибка в коде или сбой какой-то? 
В IntelliJIDEA все работает без ошибок. А в моем личном кабинете Mate постоянно крутятся кольца "как загрузка" в разделе OOP Advance и не отображает никаких надписей - не могу увидеть какой статус выполнения задания.

2021-07-09 06:42 UTC, RomanDubovskyi requested changes
Помилки з чекстайлом, локально в терміналі запусти mvn clean package (про це детальніше пояснено у відео в першому топіку)
![image](https://user-images.githubusercontent.com/58385506/125034203-01d0a080-e099-11eb-91fd-6bfc08172842.png)

2021-07-09 06:42 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/Circle.java
> +    private final static String FIGURE_NAME = "Circle";
ця змінна зайва, у нас клас вже називається Circle якщо тобі потрібна ця назва - її можна отримати через 
`Circle.class.getName()`

2021-07-09 06:42 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/Circle.java
> +    void chooseFigureColor(int randomColorNumber) {
звідси краще прибрати цей метод і розділити логіку. Ініціалізація, вибір кольору і тд повинен відбуватись у FigureSupplier, Сircle це моделька яка репрзентує круг, він не повинен залежити від ColorSupplier

2021-07-09 06:42 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/Circle.java
> +    private double circleArea;
ця змінна нам не потрібна, ми не можемо до неї достукатись за межами класу так як вона приватна і результат площі віддаємо в будь-якому випадку з calculateArea

2021-07-09 06:42 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/ColorSupplier.java
> +                break;
```suggestion
                return "Red";
```

2021-07-09 06:42 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/IsoscelesTrapezoid.java
> +    private final static String FIGURE_NAME = "IsoscelesTrapezoid";
аналогічну тут і в інших модельках

2021-07-12 07:24 UTC, RomanDubovskyi approved these changes

2021-07-12 07:24 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    private int colorNumber;
```suggestion
    private Random random = new Random();
    private static final int COLOR_NUMBER = 4;
```
Краще логіку рандому стосовно кольору перенести з FigureSupplier до ColorSupplier

2021-07-12 07:24 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        String color;
```suggestion
        int colorNumber = random.nextInt(COLOR_NUMBER);
```

2023-09-24 16:10 UTC, closed without merging