jv-oop-advanced
mate-academy/jv-oop-advanced pull request #160
Opened 2021-07-11 17:18 UTC by vbuchii

Implemented square, rectangle, right triangle, circle, isosceles trapezoid using OOP principles.

2021-07-16 12:14 UTC, RomanDubovskyi requested changes

2021-07-16 12:14 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/util/FigureSupplier.java
> +    public static void drawFigures(Figure[] figures) {
цей метод краще звідси прибрати, так як він порушує singe responsibility. Supplier відповідає лише за створення фігур

2021-07-16 12:14 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/util/FigureSupplier.java
> +    private static Figure getRandomFigure() {
я б радив уникати такої кількості статики в класах, якщо потрібно буде додавати якісь залежності то будуть потім проблем з гнучкістю і поліморфізмом

2021-07-16 12:14 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/util/FigureSupplier.java
> +            e.printStackTrace();
print stack trace погана практика

2021-07-16 12:14 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/util/Figure.java
> +                e.printStackTrace();
аналогічно

2021-07-17 13:47 UTC, vbuchii commented on src/main/java/core/basesyntax/util/FigureSupplier.java
> +    private static Figure getRandomFigure() {
Thanks for the explanation, changed it. I was thinking about that as they are utility functions and we need every time the same behavior.

2021-07-17 13:47 UTC, vbuchii commented on src/main/java/core/basesyntax/util/FigureSupplier.java
> +    public static void drawFigures(Figure[] figures) {
Done.

2021-07-17 13:47 UTC, vbuchii commented on src/main/java/core/basesyntax/util/FigureSupplier.java
> +            e.printStackTrace();
Sorry, I didn't think about that. To my understanding, you are saying about showing stack trace to the user. Changed it to use logger, which is disabled by default.

2021-07-17 13:53 UTC, vbuchii commented on src/main/java/core/basesyntax/util/Figure.java
> +                e.printStackTrace();
Did the same, please let me know if it is not what we need.

2021-07-23 08:30 UTC, MaliukDaria approved these changes

2025-08-20 09:38 UTC, closed without merging