Yegor sereda
mate-academy/jv-oop-advanced pull request #18
Opened 2020-12-02 11:16 UTC by entertainment-veks

2020-12-02 12:25 UTC, Sofasmile requested changes

2020-12-02 12:25 UTC, Sofasmile commented on src/main/java/core/basesyntax/Circle.java
> +        System.out.println("Рисую круг");
давай старатись завжди використовувати анг мову в коді

2020-12-02 12:25 UTC, Sofasmile commented on src/main/java/core/basesyntax/Circle.java
> +    public void unicMetod() {
за що відповідає цей метод? не зовсім очевидним є його призначення

2020-12-02 12:25 UTC, Sofasmile commented on src/main/java/core/basesyntax/Figure.java
> +    public abstract void draw();
краще винести цей метод в окремий інтерфейс
* interface - behavior
* abstract class - state

2020-12-02 12:25 UTC, Sofasmile commented on src/main/java/core/basesyntax/HelloWorld.java
> +        for (int i = 0; i < figures.length; i++) {
генерацію фігур краще винести в окремий клас, а тут тільки викликати цей метод

2020-12-02 12:25 UTC, Sofasmile commented on src/main/java/core/basesyntax/HelloWorld.java
> +            switch (random.nextInt(5)) {
declare 5 as a constant, now it's magic number
https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names

2020-12-02 12:25 UTC, Sofasmile commented on src/main/java/core/basesyntax/HelloWorld.java
> +            figures[i].setArea(random.nextInt(25));
давай вираховувати площу на основі даних про фігуру, а не рандомно генерувати її

2020-12-02 12:25 UTC, Sofasmile commented on src/main/java/core/basesyntax/HelloWorld.java
> +            figures[i].setColor(Color.values()[random.nextInt(3)]);
3 - чому використовуємо саме це число? Давай замінимо на довжину масиву єнамів

2020-12-02 12:25 UTC, Sofasmile commented on src/main/java/core/basesyntax/Circle.java
> +public class Circle extends Figure {
до кожного класу фігури потрібно додати його унікальні параметри. І при створенні об'єкта через конструктор ініціалізовувати їх рандомними значеннями

2020-12-02 12:31 UTC, entertainment-veks commented on src/main/java/core/basesyntax/Circle.java
> +    public void unicMetod() {
В задании написано, что у каждой фигуры должен быть уникальный метод. Это он

2020-12-02 12:34 UTC, entertainment-veks commented on src/main/java/core/basesyntax/HelloWorld.java
> +        for (int i = 0; i < figures.length; i++) {
Решил что это плохая идея плодить классы ради пары строк. Я думаю, код не настолько перегружен

2020-12-02 15:46 UTC, Sofasmile requested changes

2020-12-02 15:46 UTC, Sofasmile commented on src/main/java/core/basesyntax/Circle.java
> +public class Circle extends Figure implements Draw {
давай будемо імплементувати інтерфейс Draw в класі фігури (тоді не потрібно буде щоразу його імплементувати в кожному із класів наслідників)

2020-12-02 15:46 UTC, Sofasmile commented on src/main/java/core/basesyntax/Circle.java
> +    public void unicMetod() {
під унікальними методами малось на увазі наприклад: getRadius() для кола, getSide() для квадрата, і т.д
це не повинен бути один метод для всіз класів - їх може бути різна кількість в кожному класі, і вони повинні не змінюватись)

2020-12-02 15:46 UTC, Sofasmile commented on src/main/java/core/basesyntax/Figure.java
> +    private String name;
ми маємо доступ до цих полів? не бачу де ми до них звертаємось))
Давай спробуємо додати констуктор, або методи для збереження цих даних

2020-12-02 15:46 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureMaker.java
> +    public Figure[] makeFigures(int amount) {
дуже багато зайвих пустих строк в цьому методі)) Давай трохи повидаляємо цих ліній

2020-12-02 15:46 UTC, Sofasmile commented on src/main/java/core/basesyntax/HelloWorld.java
> +    public static final int FIGURES_TYPES = 5;
давай перенесемо цю змінну в клас де вона використовується

2020-12-02 15:46 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureMaker.java
> +                default:
дефолт зазвичай варто розміщувати після всіх case

2020-12-02 15:46 UTC, Sofasmile commented on src/main/java/core/basesyntax/IsoscelesTrapezoid.java
> +
першу лінію можна не пропускати, а писати відразу код

2020-12-02 19:00 UTC, Sofasmile requested changes

2020-12-02 19:00 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureUnicMetodSwitcher.java
> +public class FigureUnicMetodSwitcher {
цей клас можна буде прибрати коли ми видамо методи з класу фігури

2020-12-03 09:35 UTC, Sofasmile approved these changes
great job))

2021-04-01 06:08 UTC, closed without merging