Homework
mate-academy/jv-oop-advanced pull request #21
Opened 2020-12-02 14:07 UTC by YuraMitryakhin

2020-12-02 18:20 UTC, Sofasmile requested changes

2020-12-02 18:20 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureGenerate.java
> +    private void doCalculationAndGenerateColor(Figure figure) {
для чого потріьен цей метод?

2020-12-02 18:20 UTC, Sofasmile commented on src/main/java/core/basesyntax/Main.java
> +    public static void getAndPrintFigure(Figure[] figures) {
```suggestion
    private static void getAndPrintFigure(Figure[] figures) {
```

2020-12-03 07:21 UTC, YuraMitryakhin commented on src/main/java/core/basesyntax/Calculations.java
> +    void doAllCalculations();
В нас в кожному класі є мінімум два метода для обрахунків, я вирішив створити новий обов"язковий метод для виклику всіх внутрішніх підрахунків класу, ми знаємо в кожного класу є метод підрахунку площі, але ми не знаємо який ще є метод (це може бути підрахунок гіпотенузи, висоти, переметра і тд) і що б спростити життя користувачу, він просто визиває один метод(який 100% є в кожному класі) для підрахунку всіх значень

2020-12-03 07:26 UTC, YuraMitryakhin commented on src/main/java/core/basesyntax/FigureGenerate.java
> +    private void doCalculationAndGenerateColor(Figure figure) {
для того що б не повторювати виклик двох однакових функцій в кожній функції для фігур (зменщети дублювання коду), помоєму краще визивати одну функцію багато разів чим кожен раз по дві

2020-12-03 09:40 UTC, YuraMitryakhin commented on src/main/java/core/basesyntax/Calculations.java
> +    void doAllCalculations();
Щойно зробив це інакшим способом

2020-12-03 09:40 UTC, YuraMitryakhin commented on src/main/java/core/basesyntax/FigureGenerate.java
> +    private void doCalculationAndGenerateColor(Figure figure) {
Після видалення інтерфейсу в цій функції більше немає потреби

2020-12-03 10:47 UTC, Sofasmile approved these changes

2020-12-03 10:47 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureGenerate.java
> +        ;
варто видалити зайву ";"

2021-04-01 06:08 UTC, closed without merging