OOP Advanced add Solution 1
mate-academy/jv-oop-advanced pull request #228
Opened 2021-08-26 09:01 UTC by oleksandr-saulko

2022-04-20 15:42 UTC, MaliukDaria requested changes

2022-04-20 15:42 UTC, MaliukDaria commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    private Random indexOfColor = new Random();
```suggestion
    private Random random = new Random();
```

2022-04-20 15:42 UTC, MaliukDaria commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return colors[indexOfColor.nextInt(RANDOM_RANGE)];
```suggestion
        return colors[indexOfColor.nextInt(colors.length)];
```

and so we could delete RANDOM_RANGE constant

2022-04-20 15:42 UTC, MaliukDaria commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        switch (figureNumber) {
lets make 5 private methods getRandomCircle(), getRandomSquare(), ... and call them in switch-case construction

2022-04-20 15:42 UTC, MaliukDaria commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        }
lets move number 100 to constant

2022-05-17 15:52 UTC, MaliukDaria requested changes
Task: 
In the main() method we need to create an array of figures (the size of array can be 3 or 6, it doesn't matter). The first half of figures in this array should be generated with random parameters. The other half of figures should have the same, default parameters.
I cant sww this functionality

2022-05-17 15:52 UTC, MaliukDaria commented on src/main/java/core/basesyntax/DrawFigure.java
> +public interface DrawFigure {
```suggestion
public interface Drawlable {
```

as we can use this interface not only for Figures

2022-05-17 15:52 UTC, MaliukDaria commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    }
private methods should be after public as helper ones

2022-05-17 15:52 UTC, MaliukDaria commented on src/main/java/core/basesyntax/FigureSupplier.java
> +public class FigureSupplier extends ColorSupplier {
you should also implement getDefaultFigure() method (read the task)

2022-05-18 17:13 UTC, oleksandr-saulko commented
> Task: In the main() method we need to create an array of figures (the size of array can be 3 or 6, it doesn't matter). The first half of figures in this array should be generated with random parameters. The other half of figures should have the same, default parameters. I cant sww this functionality

I apologize. I made this task last summer and got merged 2 forks. I didn't saw when the main method was replaced for the base version.

2022-05-19 09:36 UTC, MaliukDaria requested changes

2022-05-19 09:36 UTC, MaliukDaria commented on src/main/java/core/basesyntax/Main.java
> +        };
lets make it in a loop?

2022-05-19 09:37 UTC, MaliukDaria commented
> > Task: In the main() method we need to create an array of figures (the size of array can be 3 or 6, it doesn't matter). The first half of figures in this array should be generated with random parameters. The other half of figures should have the same, default parameters. I cant sww this functionality
> 
> I apologize. I made this task last summer and got merged 2 forks. I didn't see when the main method was replaced for the base version.

Oh, i see) This part of task was added later 🙂

2022-05-19 12:38 UTC, MaliukDaria approved these changes
GJ

2023-06-28 05:30 UTC, closed without merging