Task with figures attempt
mate-academy/jv-oop-advanced pull request #33
Opened 2020-12-02 17:18 UTC by vicire

2020-12-02 18:53 UTC, Sofasmile requested changes
awesome)

2020-12-02 18:53 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureRandom.java
> +        int randomFigure = new Random().nextInt(5);
давай число 5 зробимо константою - https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names
бо зараз не зрозуміло чому саме 5, а не 10 наприклад

2020-12-02 18:53 UTC, Sofasmile commented on src/main/java/core/basesyntax/RandomGenerator.java
> +    public void getRandom() {
загалом цю логіку можна перенести в метод main()

2020-12-02 19:06 UTC, vicire commented on src/main/java/core/basesyntax/FigureRandom.java
> +        int randomFigure = new Random().nextInt(5);
пофіксив

2020-12-02 19:08 UTC, vicire commented on src/main/java/core/basesyntax/RandomGenerator.java
> +    public void getRandom() {
Переніс. Просто на Q & A ти казала, що в main має бути суто метод, який це все запускає. Я сприйняв надто буквально :)

2020-12-03 09:53 UTC, Sofasmile approved these changes

2020-12-03 09:53 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureRandom.java
> +    public static final int NUMBER = 5;
```suggestion
    public static final int NUMBER_OF_FIGURES = 5;
```

2021-04-01 06:11 UTC, closed without merging