oop-advanced task done
mate-academy/jv-oop-advanced pull request #37
Opened 2020-12-02 19:00 UTC by less08

2020-12-02 19:11 UTC, Sofasmile requested changes

2020-12-02 19:11 UTC, Sofasmile commented on src/main/java/core/basesyntax/Circle.java
> +
тут не варто залишати пусту строку

2020-12-02 19:11 UTC, Sofasmile commented on src/main/java/core/basesyntax/Circle.java
> +    Circle(double radius, Colour colour) {
варто додати модифікатор доступу

2020-12-02 19:11 UTC, Sofasmile commented on src/main/java/core/basesyntax/RandomShapeProducer.java
> +        int randomGeneratedIndex = new Random().nextInt(5);
давай 5 оголосимо як константу) https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names

2020-12-02 19:11 UTC, Sofasmile commented on src/main/java/core/basesyntax/Shape.java
> +    protected Colour colour;
варто поле зробити приватним. А щоб мати доступ до нього можна зробити конструктор і приймати його як параметр. А в дочірних класах викликати цей конструктор за допомогою super(color)

2020-12-02 19:11 UTC, Sofasmile commented on src/main/java/core/basesyntax/Shape.java
> +    public abstract void draw();
давай перенесемо цей метод в окремий інтерфейс та імплементуємо цей інтерфейс в класі Shape, а методи перевизначимо в класах наслідниках

2020-12-02 19:17 UTC, less08 commented on src/main/java/core/basesyntax/Shape.java
> +    public abstract void draw();
Окей, сделаю. Но хочу спросить, не будет ли это излишеством? Или это как правило хорошего программирования?
Или это для того, чтобы научиться использовать и абстрактные классы, и интерфейсы?)

2020-12-03 09:50 UTC, Sofasmile commented on src/main/java/core/basesyntax/RandomShapeProducer.java
> +    static final int NUMBER_OF_SHAPES = 5;
```suggestion
    private static final int NUMBER_OF_SHAPES = 5;
```

2020-12-03 09:50 UTC, Sofasmile commented on src/main/java/core/basesyntax/Shape.java
> +    public abstract void draw();
В програмуванні потрібно завжди відштовхуватись від двох принципів - правильна архітектура коду (щоб в майбутньому код можна було перевикористовувати і розширювати) та принцип KISS. В даному випадку це відносить більше до правильної архітектури

2020-12-03 09:50 UTC, Sofasmile requested changes
awesome

2020-12-03 09:51 UTC, Sofasmile approved these changes

2021-04-01 06:11 UTC, closed without merging