Full solved task with all business-logic
mate-academy/jv-oop-advanced pull request #590
Opened 2022-07-28 19:27 UTC by AndrewHudzenko

2022-07-29 06:42 UTC, Noct2000 requested changes

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/AllOurFigures.java
> +public enum AllOurFigures {
I think this is not the best naming for enum

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/Circle.java
> +//Circle has index 4
```suggestion
```

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/Circle.java
> +        return 2 * Math.PI * radius;
```suggestion
        return Math.PI * radius * radius;
```

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/Drawing.java
> +public interface Drawing {
don't use action in interface naming
```suggestion
public interface Drawable {
```

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/CalculatingArea.java
> +public interface CalculatingArea {
don't use action in interface naming

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/FigureSupplier.java
> +                .nextInt(AllOurFigures.values().length)].toString();
you can use an enum instead of a String in swich-case

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        return new Circle("WHITE", CIRCLE_DEFAULT_RADIUS);
replace "WHITE" with your_enum.WHITE.name()

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/IsoscelesTrapezoid.java
> +//IsoscelesTrapezoid has index 5
```suggestion
```

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/Main.java
> +            if (i >= 3) {
replace 6 with a constant and 3 with half a constant

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/Rectangle.java
> +//Rectangle has index 2
```suggestion
```

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private static final int MAX_RANDOM_NUMBER_RANGE_FOR_FIGURE_SIDES = 100;
I think this name is too long

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/RightTriangle.java
> +//RightTriangle has index 3
```suggestion
```

2022-07-29 06:42 UTC, Noct2000 commented on src/main/java/core/basesyntax/Square.java
> +//Square has index 1
```suggestion
```

2022-08-01 10:26 UTC, KseniiaMakarova requested changes

2022-08-01 10:26 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Calculational.java
> +    double getFigureArea();
```suggestion
    double getArea();
```
let's not attach method name to Figure

2022-08-01 10:26 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Drawable.java
> +    void drawFigure();
```suggestion
    void draw();
```
same

2022-08-01 10:26 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Rectangle.java
> +    private double sideB;
```suggestion
    private double length;
    private double height;
```

2022-08-01 10:26 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Square.java
> +    private double sideA;
```suggestion
    private double side;
```

2022-08-01 12:48 UTC, KseniiaMakarova requested changes

2022-08-01 12:48 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        Figure randomFigure = Figure.values()[new Random()
```suggestion
        Figure randomFigure = Figure.values()[random
```

2022-08-01 12:48 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Rectangle.java
> +        this.height = sideB;
rename constructor params

2022-08-01 12:48 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Square.java
> +        this.side = sideA;
same

2024-04-11 16:41 UTC, closed without merging