My home work oop advanced
mate-academy/jv-oop-advanced pull request #597
Opened 2022-07-29 09:42 UTC by fifahater

2022-07-29 13:12 UTC, Sofasmile requested changes

2022-07-29 13:12 UTC, Sofasmile commented on src/main/java/core/basesyntax/Draw.java
> +    public abstract String getDraw();
```suggestion
    String getDraw();
```
`public abstract` are default values for methods in the interface so that we can remove them

2022-07-29 13:12 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureSupplier.java
> +public class FigureSupplier extends ColorSupplier {
```suggestion
public class FigureSupplier {
```

2022-07-29 13:12 UTC, Sofasmile commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private static final int INDEX = 5;
```suggestion
    private static final int NUMBER_OF_FIGURS = 5;
```

2022-08-01 07:57 UTC, dSkarzh requested changes
nice start

2022-08-01 07:57 UTC, dSkarzh commented on src/main/java/core/basesyntax/Color.java
> +    PINK;
```suggestion
    PINK
```

2022-08-01 07:57 UTC, dSkarzh commented on src/main/java/core/basesyntax/Drawable.java
> +    String getDraw();
```suggestion
    void draw();
```

2022-08-01 07:57 UTC, dSkarzh commented on src/main/java/core/basesyntax/Drawable.java
> +    String getDraw();
this method should print information

2022-08-01 07:57 UTC, dSkarzh commented on src/main/java/core/basesyntax/figure/Circle.java
> +    }
```suggestion
    public void draw() {
        System.out.println("information about figure here");
    }
```

2022-08-01 07:57 UTC, dSkarzh commented on src/main/java/core/basesyntax/figure/Circle.java
> +    }
the same for all `getDraw()` usages

2022-08-01 07:57 UTC, dSkarzh commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        ColorSupplier colorSupplier = new ColorSupplier();
let's move this to field level so we don't create objects each time we call `getRandomFigure()`

2022-08-01 07:57 UTC, dSkarzh commented on src/main/java/core/basesyntax/Main.java
> +    private static final int NUMBER_OF_DEFAULT_FIGURES = 3;
let's use only one constant because number of default figures is always half of the total number of figures

2022-08-01 07:57 UTC, dSkarzh commented on src/main/java/core/basesyntax/Main.java
> +    }
rewrite this using `draw()`

2022-08-01 09:35 UTC, dSkarzh approved these changes

2024-09-17 20:28 UTC, closed without merging