Fixing bugs rev2
mate-academy/jv-oop-advanced pull request #603
Opened 2022-07-29 15:18 UTC by ValeriyM250

I didn`t understand entirely "Ми можемо створити 5 приватних методів getRandomCircle(), getRandomSquare() ... і викликати їх у конструкції switch-case." and that`s why I did task in the next way.
 If my decision will be ok - approve this task, if not - please explain for me how I have to fix.
 I can`t name fields "DefaultColor" and "DefaultRadius" as "DEFAULT_COLOR" & "DEFAULT_RADIUS", because I have these messages:
  Abbreviation in name 'DEFAULT_COLOR' must contain no more than '2' consecutive capital letters. [AbbreviationAsWordInName]
  Member name 'DEFAULT_COLOR' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$' [MemberName]
  Abbreviation in name 'DEFAULT_RADIUS' must contain no more than '2' consecutive capital letters. [AbbreviationAsWordInName]
 Member name 'DEFAULT_RADIUS' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [MemberName]

2022-07-29 15:41 UTC, MaliukDaria requested changes

2022-07-29 15:41 UTC, MaliukDaria commented on src/main/java/core/basesyntax/temp/Figure.java
> +    }
Чи потрібні нам тут ці методи?

2022-07-29 15:41 UTC, MaliukDaria commented on src/main/java/core/basesyntax/temp/AreaCalculator.java
> +    public abstract void getArea();
```suggestion
    Double getArea();
```

всі методи без реалізації в інтерфейсі public abstract  за замовчуванням

2022-07-29 15:41 UTC, MaliukDaria commented on src/main/java/core/basesyntax/Main.java
> +    }
```suggestion
        FigureSupplier figureSupplier = new FigureSupplier();
        Figure [] figure = new Figure[6];
        for (int i = 0; i < figure.length; i++) {
            figure[i] = (figure.length / 2 > i)
                    ? figureSupplier.getRandomFigure() : figureSupplier.getDefaultFigure();
            figure[i].draw();
        }
    }
```

2022-07-29 15:41 UTC, MaliukDaria commented on src/main/java/core/basesyntax/figures/Circle.java
> +    private double figureArea;
```suggestion
public class Circle extends Figure {
    private double radius;
```

нам не потрібне поле для площі, так як ми рахуємо її динамічно за допомогою методу getArea() (який має рахувати площу і повертати її значення в якості вихідного параметру)

2022-07-29 15:41 UTC, MaliukDaria commented on src/main/java/core/basesyntax/temp/ColorSupplier.java
> +}
```suggestion
public class ColorSupplier {
    private Random random = new Random();

    public String getRandomColor() {
        int index = random.nextInt(Color.values().length);
        return Color.values()[index].name();
    }
}
```

2022-07-29 15:41 UTC, MaliukDaria commented on src/main/java/core/basesyntax/temp/Drawable.java
> +    public abstract void draw();
```suggestion
    void draw();
```

2022-07-29 15:41 UTC, MaliukDaria commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +    private final double defaultRadius = 10.0;
https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names

2022-07-29 15:41 UTC, MaliukDaria commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +    private int index = 0;
я думаю ми можемо зробити змінну index локальною

2022-07-29 15:41 UTC, MaliukDaria commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +    private Figure figure = new Circle();
те саме, давай зробимо змінну `private Figure figure` локальною

2022-07-29 15:41 UTC, MaliukDaria commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +        return figure;
```suggestion
        int figureNumber = random.nextInt(FIGURE_AMOUNT);
        switch (figureNumber) {
            case 0:
                return getRandomCircle();
            case 1:
                return getRandomIsoscelesTrapezoid();
            case 2:
                return getRandomRectangle();
            case 3:
                return getRandomRightTriangle();
            default:
                return getRandomSquare();
        }
```

2022-08-02 13:01 UTC, Nick97-git requested changes

2022-08-02 13:01 UTC, Nick97-git commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +        return figure;
```suggestion
        int figureNumber = random.nextInt(FIGURE_AMOUNT);
        switch (figureNumber) {
            case 0:
                return getRandomCircle();
            case 1:
                return getRandomIsoscelesTrapezoid();
            case 2:
                return getRandomRectangle();
            case 3:
                return getRandomRightTriangle();
            default:
                return getRandomSquare();
        }
```

2022-08-02 13:01 UTC, Nick97-git commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +        return figure;
```suggestion
        return circle
```
the same for methods below

2022-08-02 13:01 UTC, Nick97-git commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +        circle.getArea();
remove this line, the same for methods below

2022-08-02 13:01 UTC, Nick97-git commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +    public Figure getRandomCircle() {
```suggestion
    private Figure getRandomCircle() {
```

2022-08-02 13:01 UTC, Nick97-git commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +    private Figure getRandomIsoscelesTrapezoid() {
private methods should go after public ones

2022-08-03 04:33 UTC, Nick97-git requested changes
you didn't resolve several comments from my previous review, fix them

2022-08-05 10:07 UTC, Nick97-git requested changes

2022-08-05 10:07 UTC, Nick97-git commented on src/main/java/core/basesyntax/figures/Circle.java
> +    }
you don't need to override this method, remove it, you can use it and without overriding

2022-08-05 10:07 UTC, Nick97-git commented on src/main/java/core/basesyntax/Main.java
> +        Figure [] figure = new Figure[6];
```suggestion
        Figure[] figures = new Figure[6];
```

2022-08-05 10:07 UTC, Nick97-git commented on src/main/java/core/basesyntax/temp/Figure.java
> +
remove empty line

2022-08-05 10:07 UTC, Nick97-git commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +    public static final int FIGURE_AMOUNT = 4;
public -> private

2022-08-05 10:07 UTC, Nick97-git commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +    public static final int FIGURE_AMOUNT = 4;
```suggestion
    public static final String DEFAULT_COLOR = Color.WHITE.name();
    public static final double DEFAULT_RADIUS = 10.0;
    public static final int FIGURE_AMOUNT = 5;
```

2022-08-05 10:07 UTC, Nick97-git commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +
remove empty lines

2022-08-05 10:07 UTC, Nick97-git commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +            case (3):
remove brackets around numbers

2022-08-05 10:07 UTC, Nick97-git commented on src/main/java/core/basesyntax/temp/FigureSupplier.java
> +        Figure figure = new Circle();
remove this unused variable

2022-08-18 06:20 UTC, Nick97-git approved these changes

2024-09-03 05:56 UTC, closed without merging