done
mate-academy/jv-oop-advanced pull request #634
Opened 2022-08-17 13:34 UTC by not4und

2022-08-18 06:41 UTC, Nick97-git requested changes

2022-08-18 06:41 UTC, Nick97-git commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Color.values()[new Random().nextInt(Color.values().length)].name();
make a global Random field and use it here

2022-08-18 06:41 UTC, Nick97-git commented on src/main/java/core/basesyntax/Figure.java
> +    public StringBuilder getSizes() {
remove this method you don't need it, if you want to use StringBulider use it directly in every figure

2022-08-18 06:41 UTC, Nick97-git commented on src/main/java/core/basesyntax/Figure.java
> +    public void draw() {
you should've implement in this method in each figure, not here

2022-08-18 06:41 UTC, Nick97-git commented on src/main/java/core/basesyntax/Figure.java
> +    public abstract double area();
create a separate interface for this method + think about better naming, names of methods should start with a verb not noun

2022-08-18 06:41 UTC, Nick97-git commented on src/main/java/core/basesyntax/FigureForm.java
> +public enum FigureForm {
```suggestion
public enum FigureType {
```

2022-08-18 06:41 UTC, Nick97-git commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private static final int MAX_SIZE_LENGTH = 25;
```suggestion
    private static final int MAX_RANDOM_NUMBER = 25;
```

2022-08-18 06:41 UTC, Nick97-git commented on src/main/java/core/basesyntax/FigureSupplier.java
> +
remove empty line

2022-08-18 06:41 UTC, Nick97-git commented on src/main/java/core/basesyntax/FigureSupplier.java
> +public class FigureSupplier {
I don't see this method here
![Screenshot 2022-08-18 at 09 40 02](https://user-images.githubusercontent.com/60258373/185313244-1145023e-5699-4802-95be-b0c1953eed99.png)

2022-08-18 06:41 UTC, Nick97-git commented on src/main/java/core/basesyntax/FigureSupplier.java
> +                );
create a separate method for each figure that will be returning a random figure, for example, getRandomSquare() and so on

2022-08-18 14:54 UTC, kozhukhovsky requested changes

2022-08-18 14:54 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/AreaCalculate.java
> +public interface AreaCalculate {
Don’t use verbs for class/interface names.
`public interface AreaCalculator`

2022-08-18 14:54 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    private static Random random = new Random();
Do we need static here?

2022-08-18 14:54 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Figure.java
> +    private final String color;
Do we need final here? What if u want change color?

2022-08-18 14:54 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Main.java
> +                new Square("cyan", 9),
The other half of figures should have the same, default parameters.

2022-08-19 14:18 UTC, aaananas requested changes

2022-08-19 14:18 UTC, aaananas commented on src/main/java/core/basesyntax/Circle.java
> +    private final int radius;
```suggestion
    private int radius;
```
there is no need to make this field final

2022-08-19 14:18 UTC, aaananas commented on src/main/java/core/basesyntax/Square.java
> +    private final int side;
```suggestion
    private int side;
```

2022-08-19 14:18 UTC, aaananas commented on src/main/java/core/basesyntax/RightTriangle.java
> +    private final int secondLeg;
```suggestion
    private int firstLeg;
    private int secondLeg;
```

2022-08-19 14:18 UTC, aaananas commented on src/main/java/core/basesyntax/Rectangle.java
> +    private final int shortSide;
```suggestion
    private int longSide;
    private int shortSide;
```

2022-08-19 16:28 UTC, aaananas approved these changes

2023-05-08 06:57 UTC, closed without merging