jv-oop advanced
mate-academy/jv-oop-advanced pull request #778
Opened 2022-11-14 15:26 UTC by Andrei-Bondarenko-MRPL

2022-11-14 15:34 UTC, aaananas requested changes
<img width="773" alt="image" src="https://user-images.githubusercontent.com/81781479/201700677-8aa158cd-bd30-419a-aaa6-3060e6394245.png">

run `mvn clean package`

2022-11-15 17:22 UTC, zachar-chorny requested changes

2022-11-15 17:22 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private Figure[] figure = new Figure[5];
Instead of this array, use switch/case to get a random figure based on a random number

2022-11-15 17:22 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        return figure[4];
```suggestion
        return new Circle(Color.WHITE.name().toLowerCase(), 10.0);;
```
Also create a constant for 10.0

2022-11-15 17:22 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    }
Lets create private methods to create each figure

2022-11-15 17:22 UTC, zachar-chorny commented on src/main/java/core/basesyntax/Main.java
> +        figureSupplier.getDefaultFigure().draw();
<img width="841" alt="Screen Shot 2022-11-15 at 7 19 23 PM" src="https://user-images.githubusercontent.com/90692308/201984754-0e8875d5-d295-492f-88a1-7217008674ad.png">

2022-11-15 17:22 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureInfo.java
> +public interface FigureInfo {
```suggestion
public interface Drawable {
```

2022-11-15 17:22 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureArea.java
> +public interface FigureArea {
```suggestion
public interface AreaCalculator {
```

2022-11-15 17:22 UTC, zachar-chorny commented on src/main/java/core/basesyntax/Figure.java
> +    void draw();
Why you have two interfaces with draw method? Remove this one

2022-11-15 17:22 UTC, zachar-chorny commented on src/main/java/core/basesyntax/ColorFigure.java
> +public class ColorFigure implements Figure, FigureArea {
```suggestion
public class Figure implements Drawable, FigureArea {
```

2022-11-15 17:22 UTC, zachar-chorny commented on src/main/java/core/basesyntax/ColorFigure.java
> +    }
```suggestion
```

2023-04-15 19:24 UTC, closed without merging