Homework OOP Advanced
mate-academy/jv-oop-advanced pull request #840
Opened 2022-12-25 11:15 UTC by vojtcekhovski

2022-12-25 15:07 UTC, zachar-chorny requested changes

2022-12-25 15:07 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureArea.java
> +interface FigureArea {
```suggestion
public interface AreaCalculator {
```

2022-12-25 15:07 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureDrawable.java
> +public interface FigureDrawable {
```suggestion
public interface Drawable {

```

2022-12-25 15:07 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        ColorSupplier colorSupplier = new ColorSupplier();
make these variables a class-fields, like in your ColorSupplier

2022-12-25 15:07 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        }
lets create constants for magic numbers(5, 100)

2022-12-25 15:07 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        return new Circle(Color.WHITE, 10);
also create constants for White and 10

2022-12-25 15:07 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureSupplier.java
> +                return getDefaultFigure();
create private methods to create each figure and use them here

2022-12-25 15:07 UTC, zachar-chorny commented on src/main/java/core/basesyntax/FigureSupplier.java
> +
empty line

2022-12-25 15:07 UTC, zachar-chorny commented on src/main/java/core/basesyntax/Main.java
> +        figures[5] = figureSupplier.getDefaultFigure();
lets use loop for it

2023-01-02 10:51 UTC, aleksandr-bevza requested changes

2023-01-02 10:51 UTC, aleksandr-bevza commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private final Random random = new Random(System.currentTimeMillis());
I think this is not needed
```suggestion
    private final Random random = new Random();

```

2023-01-02 10:51 UTC, aleksandr-bevza commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    private final int defaultRadius = 10;
Please follow the rules of constants naming
```suggestion
    private static final int RANDOM_MAX_VALUE = 100;
    private static final int DEFAULT_RADIUS = 10;
```

2023-01-02 10:51 UTC, aleksandr-bevza commented on src/main/java/core/basesyntax/FigureSupplier.java
> +    public Figure getRandomFigure() {
Not fixed. Please create private methods for each figure creation.
![image](https://user-images.githubusercontent.com/117547096/210219917-9773ec7f-c955-4a9e-bf09-7e0f06def4b4.png)

2023-01-02 10:51 UTC, aleksandr-bevza commented on src/main/java/core/basesyntax/FigureSupplier.java
> +        Color defaultColor = Color.WHITE;
Create default color as constant, move it to class field:
private static final Color DEFAULT_COLOR = Color.WHITE;

2023-01-29 09:40 UTC, vojtcekhovski commented
Create default color as constant and create private methods for each figure

2023-01-29 09:41 UTC, vojtcekhovski reviewed
Create default color as constant and create private methods for each figure

2023-01-30 13:09 UTC, okuzan requested changes

2023-01-30 13:09 UTC, okuzan commented on src/main/java/core/basesyntax/FigureSupplier.java
> +
private members should go after public ones

2023-01-30 13:09 UTC, okuzan commented on src/main/java/core/basesyntax/Main.java
> +        }
no need to iterate twice, you can call it in the first loop

2023-01-30 13:09 UTC, okuzan commented on src/main/java/core/basesyntax/IsoscelesTrapezoid.java
> +    private double median;
better include two parallel sides, the median can be calculated based on them. How we don't have complete info about a figure

2023-01-30 13:09 UTC, okuzan commented on src/main/java/core/basesyntax/Drawable.java
> +    void drawFigure();
```suggestion
    void draw();

```

2023-02-05 16:02 UTC, vojtcekhovski reviewed
include two parallel sides, private members go after public ones

2023-02-20 18:20 UTC, olekskov requested changes

2023-02-20 18:20 UTC, olekskov commented on src/main/java/core/basesyntax/Main.java
> +                figures[i].draw();
.draw() method called in any case so should be extracted from condition block

2023-02-22 11:14 UTC, olekskov requested changes

2023-02-22 11:14 UTC, olekskov commented on src/main/java/core/basesyntax/Main.java
> +            }
Sorry, maybe I wasn't clear enough. Previous version with .draw() method usage was correct in general.
What were required to do is just extract it from conditions to use one time. Like:
if (condition) {
    figures[I] = ...
} else {
    figures[I] = ...
}
figures[I].draw()

2023-03-06 08:29 UTC, closed without merging